// Generated by StaticGenerators/PinnedArrayGenerator.cs

#if ENABLE_MONO || ENABLE_IL2CPP
#define MORPEH_UNITY
#endif

namespace Scellecs.Morpeh.Collections {
    using System;
    using System.Runtime.CompilerServices;
#if MORPEH_UNITY
    using Unity.Collections.LowLevel.Unsafe;
#else
    using System.Runtime.InteropServices;
#endif
    using Unity.IL2CPP.CompilerServices;

    // START: Extra usings

    // END: Extra usings

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.DivideByZeroChecks, false)]
    public unsafe struct LongPinnedArray : IDisposable {
        public long[] data;
        public long* ptr;
#if MORPEH_UNITY
        public ulong handle;
#else
        public GCHandle handle;
#endif
        
        public long this[long index] {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => this.data[index];
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set => this.data[index] = value;
        }
        
        public long Length => this.data.Length;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public LongPinnedArray(long size) {
            this.data = new long[size];
#if MORPEH_UNITY
            this.ptr = (long*)UnsafeUtility.PinGCArrayAndGetDataAddress(this.data, out this.handle);
#else
            this.handle = GCHandle.Alloc(this.data, GCHandleType.Pinned);
            this.ptr = (long*)this.handle.AddrOfPinnedObject();
#endif
        }

        [MethodImpl(MethodImplOptions.NoInlining)]
        public void Resize(long newSize) {
#if MORPEH_UNITY
            UnsafeUtility.ReleaseGCObject(this.handle);
#else
            this.handle.Free();
#endif
            var newArray = new long[newSize];
            var len = this.data.Length;
            Array.Copy(this.data, 0, newArray, 0, newSize >= len ? len : newSize);
            this.data = newArray;
#if MORPEH_UNITY
            this.ptr = (long*)UnsafeUtility.PinGCArrayAndGetDataAddress(this.data, out this.handle);
#else
            this.handle = GCHandle.Alloc(newArray, GCHandleType.Pinned);
            this.ptr = (long*)this.handle.AddrOfPinnedObject();
#endif
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Clear() {
            Array.Clear(this.data, 0, this.data.Length);
        }
        
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Dispose() {
#if MORPEH_UNITY
            UnsafeUtility.ReleaseGCObject(this.handle);
            this.ptr = (long*)IntPtr.Zero;
            this.data = null;
#else
            if (this.handle.IsAllocated) {
                this.handle.Free();
                this.ptr = (long*)IntPtr.Zero;
                this.data = null;
            }
#endif
        }

        // START: Enumerator
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public Enumerator GetEnumerator() {
            Enumerator e;
            e.index  = -1;
            e.length = this.data.Length;
            e.ptr = this.ptr;
            return e;
        }
        
        [Il2CppSetOption(Option.NullChecks, false)]
        [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
        [Il2CppSetOption(Option.DivideByZeroChecks, false)]
        public struct Enumerator {
            public long index;
            public long length;
            public long* ptr;

            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            public bool MoveNext() {
                return ++this.index < this.length;
            }

            public long Current {
                [MethodImpl(MethodImplOptions.AggressiveInlining)]
                get => this.ptr[this.index];
            }
        }
        // END: Enumerator
    }
}
